import React from 'react';
import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = (props) => {
	const {texts} = props
	console.log(Object.keys(props))
	return (
		<div className={styles.container}>
			<Head>
				<title>Fossil Fuel Registry</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					{texts.grff}
				</h1>
			</main>
		</div>
	)
}

export default Home;

export {getCommonStaticProps as getStaticProps} from '../lib/getCommonStaticProps'